/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.vincent.petadoptionsystem.ui;


import com.vincent.petadoptionsystem.service.PetAdoptionSystem;

import com.vincent.petadoptionsystem.model.AdoptionApplication;
import com.vincent.petadoptionsystem.model.Pet;
import com.vincent.petadoptionsystem.model.User;
import com.vincent.petadoptionsystem.service.PetAdoptionSystem;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author vincent
 */
public class AdopterFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdopterFrame.class.getName());
private final PetAdoptionSystem system;
private final User currentUser;
private boolean showingPetList = false;
    /**
     * Creates new form AdopterFrame
     * @param user
     */
 public AdopterFrame(User user) {
    initComponents();
    system = PetAdoptionSystem.getInstance();
    this.currentUser = user;

    ViewButton.addActionListener(this::ViewButtonActionPerformed);
    LogoutButton.addActionListener(this::LogoutButtonActionPerformed);

    petTable.setModel(new DefaultTableModel(
        new Object[][]{},
        new String[]{
            "Pet ID", "Name", "Species", "Breed", "Age",
            "Gender", "Color", "Health Status", "Adoption Status"
        }
    ));

    setLocationRelativeTo(null);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        AdopterLabel = new javax.swing.JLabel();
        BrowsePetsButton = new javax.swing.JButton();
        ViewButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();
        PetPane = new javax.swing.JScrollPane();
        petTable = new javax.swing.JTable();
        SubmitApplicationButton = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AdopterLabel.setText("Adopter Dashboard");

        BrowsePetsButton.setText("Browse Pets");
        BrowsePetsButton.addActionListener(this::BrowsePetsButtonActionPerformed);

        ViewButton.setText("View My Applications");

        LogoutButton.setText("Logout");

        petTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        PetPane.setViewportView(petTable);

        SubmitApplicationButton.setText("Submit Adoption Application");
        SubmitApplicationButton.addActionListener(this::SubmitApplicationButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(AdopterLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ViewButton)
                            .addComponent(BrowsePetsButton)
                            .addComponent(LogoutButton)
                            .addComponent(SubmitApplicationButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addComponent(PetPane, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AdopterLabel)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(PetPane, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(30, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(BrowsePetsButton)
                        .addGap(44, 44, 44)
                        .addComponent(ViewButton)
                        .addGap(35, 35, 35)
                        .addComponent(LogoutButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SubmitApplicationButton)
                        .addGap(107, 107, 107))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BrowsePetsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrowsePetsButtonActionPerformed
        // TODO add your handling code here:
        
   
    List<Pet> petList = system.getAvailablePets();
    showingPetList = true;

    DefaultTableModel model = new DefaultTableModel();
    model.setColumnIdentifiers(new String[]{
        "Pet ID", "Name", "Species", "Breed", "Age",
        "Gender", "Color", "Health Status", "Adoption Status"
    });

    for (Pet pet : petList) {
        model.addRow(new Object[]{
            pet.getPetId(),
            pet.getName(),
            pet.getSpecies(),
            pet.getBreed(),
            pet.getAge(),
            pet.getGender(),
            pet.getColor(),
            pet.getHealthStatus(),
            pet.getAdoptionStatus()
        });
    }

    petTable.setModel(model);

    }//GEN-LAST:event_BrowsePetsButtonActionPerformed

    private void SubmitApplicationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitApplicationButtonActionPerformed
        // TODO add your handling code here:
        
   
    if (!showingPetList) {
        JOptionPane.showMessageDialog(this, "Please click Browse Pets first, then select a pet.");
        return;
    }

    int selectedRow = petTable.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a pet first.");
        return;
    }

    Object petIdValue = petTable.getValueAt(selectedRow, 0);

    if (petIdValue == null) {
        JOptionPane.showMessageDialog(this, "Selected row is empty. Please click Browse Pets first and choose a valid pet.");
        return;
    }

    int petId = Integer.parseInt(petIdValue.toString());

    boolean success = system.createAdoptionApplication(currentUser.getUserId(), petId);

    if (success) {
        JOptionPane.showMessageDialog(this, "Adoption application submitted successfully!");
    } else {
        JOptionPane.showMessageDialog(this, "Failed to submit application.");
    }



    }//GEN-LAST:event_SubmitApplicationButtonActionPerformed
private void ViewButtonActionPerformed(java.awt.event.ActionEvent evt) {
    List<AdoptionApplication> applicationList =
            system.getApplicationsByUserId(currentUser.getUserId());

    showingPetList = false;

    DefaultTableModel model = new DefaultTableModel();
    model.setColumnIdentifiers(new String[]{
        "Pet ID", "Pet Name", "Species", "Breed", "Status"
    });

    for (AdoptionApplication application : applicationList) {
        model.addRow(new Object[]{
            application.getPetId(),
            application.getPetName(),
            application.getSpecies(),
            application.getBreed(),
            application.getStatus()
        });
    }

    petTable.setModel(model);

    if (applicationList.isEmpty()) {
        JOptionPane.showMessageDialog(this, "You have not submitted any adoption applications yet.");
    }
}
private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {
    new MainFrame().setVisible(true);
    this.dispose();
}
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdopterLabel;
    private javax.swing.JButton BrowsePetsButton;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JScrollPane PetPane;
    private javax.swing.JButton SubmitApplicationButton;
    private javax.swing.JButton ViewButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable petTable;
    // End of variables declaration//GEN-END:variables

}