/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.vincent.petadoptionsystem.ui;


/**
 * Dashboard for adopter users.
 * This class allows adopters to manage their profile, browse available pets,
 * submit adoption applications, view application status, and withdraw applications.
 *
 * @author Yuedong Xu
 * @version demo final version
 */

import com.vincent.petadoptionsystem.model.AdoptionApplication;
import com.vincent.petadoptionsystem.model.Pet;
import com.vincent.petadoptionsystem.model.User;
import com.vincent.petadoptionsystem.service.PetAdoptionSystem;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.vincent.petadoptionsystem.model.AdopterProfile;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.SpinnerNumberModel;

public class AdopterFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdopterFrame.class.getName());
private final PetAdoptionSystem system;
private final User currentUser;
private boolean showingPetList = false;
    /**
     * Creates new form AdopterFrame
     * @param user
     */
public AdopterFrame(User user) {
    initComponents();
    system = PetAdoptionSystem.getInstance();
    this.currentUser = user;

    LogoutButton.addActionListener(this::LogoutButtonActionPerformed);

    petTable.setModel(new DefaultTableModel(
        new Object[][]{},
        new String[]{
            "Pet ID", "Name", "Species", "Breed", "Age",
            "Gender", "Color", "Health Status", "Adoption Status"
        }
    ));

    setLocationRelativeTo(null);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        AdopterLabel = new javax.swing.JLabel();
        BrowsePetsButton = new javax.swing.JButton();
        ViewButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();
        PetPane = new javax.swing.JScrollPane();
        petTable = new javax.swing.JTable();
        SubmitApplicationButton = new javax.swing.JButton();
        ManageProfileButton = new javax.swing.JButton();
        WithdrawApplicationButton = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AdopterLabel.setText("Adopter Dashboard");

        BrowsePetsButton.setText("Browse Pets");
        BrowsePetsButton.addActionListener(this::BrowsePetsButtonActionPerformed);

        ViewButton.setText("View My Applications");
        ViewButton.addActionListener(this::ViewButtonActionPerformed);

        LogoutButton.setText("Logout");

        petTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        PetPane.setViewportView(petTable);

        SubmitApplicationButton.setText("Submit Adoption Application");
        SubmitApplicationButton.addActionListener(this::SubmitApplicationButtonActionPerformed);

        ManageProfileButton.setText("Register / Manage Profile");
        ManageProfileButton.addActionListener(this::ManageProfileButtonActionPerformed);

        WithdrawApplicationButton.setText("Withdraw Selected Application");
        WithdrawApplicationButton.addActionListener(this::WithdrawApplicationButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(AdopterLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ViewButton)
                            .addComponent(BrowsePetsButton)
                            .addComponent(LogoutButton)
                            .addComponent(SubmitApplicationButton)
                            .addComponent(ManageProfileButton)
                            .addComponent(WithdrawApplicationButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(PetPane, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AdopterLabel)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(PetPane, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(30, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(BrowsePetsButton)
                        .addGap(44, 44, 44)
                        .addComponent(ViewButton)
                        .addGap(101, 101, 101)
                        .addComponent(ManageProfileButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SubmitApplicationButton)
                        .addGap(18, 18, 18)
                        .addComponent(WithdrawApplicationButton)
                        .addGap(43, 43, 43)
                        .addComponent(LogoutButton)
                        .addGap(39, 39, 39))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BrowsePetsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrowsePetsButtonActionPerformed
        // TODO add your handling code here:
    loadAvailablePets();

    }//GEN-LAST:event_BrowsePetsButtonActionPerformed
private void loadAvailablePets() {
    List<Pet> petList = system.getAvailablePets();
    showingPetList = true;

    DefaultTableModel model = new DefaultTableModel();
    model.setColumnIdentifiers(new String[]{
        "Pet ID", "Name", "Species", "Breed", "Age",
        "Gender", "Color", "Health Status", "Adoption Status"
    });

    for (Pet pet : petList) {
        model.addRow(new Object[]{
            pet.getPetId(),
            pet.getName(),
            pet.getSpecies(),
            pet.getBreed(),
            pet.getAge(),
            pet.getGender(),
            pet.getColor(),
            pet.getHealthStatus(),
            pet.getAdoptionStatus()
        });
    }

    petTable.setModel(model);
}private boolean isAdopterProfileComplete(AdopterProfile profile) {
    return profile != null
            && profile.getMonthlyIncome() != null
            && profile.getLivingArea() != null && !profile.getLivingArea().trim().isEmpty()
            && profile.getPetRaisingExperience() != null && !profile.getPetRaisingExperience().trim().isEmpty()
            && profile.getNumberOfPeople() != null
            && profile.getPreferredPetType() != null && !profile.getPreferredPetType().trim().isEmpty();
}
    private void SubmitApplicationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitApplicationButtonActionPerformed
        // TODO add your handling code here:
        
   AdopterProfile profile = system.getAdopterProfileByUserId(currentUser.getUserId());

if (!isAdopterProfileComplete(profile)) {
    JOptionPane.showMessageDialog(
            this,
            "Please complete your adopter profile before submitting an adoption application."
    );
    return;
}
    if (!showingPetList) {
        JOptionPane.showMessageDialog(this, "Please click Browse Pets first, then select a pet.");
        return;
    }

    int selectedRow = petTable.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a pet first.");
        return;
    }

    Object petIdValue = petTable.getValueAt(selectedRow, 0);

    if (petIdValue == null) {
        JOptionPane.showMessageDialog(this, "Selected row is empty. Please click Browse Pets first and choose a valid pet.");
        return;
    }

    int petId = Integer.parseInt(petIdValue.toString());

    boolean success = system.createAdoptionApplication(currentUser.getUserId(), petId);

    if (success) {
    JOptionPane.showMessageDialog(this, "Adoption application submitted successfully!");
    loadAvailablePets();
} else {
    JOptionPane.showMessageDialog(this, "Application failed. You may have already applied for this pet.");
}



    }//GEN-LAST:event_SubmitApplicationButtonActionPerformed

    private void ManageProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageProfileButtonActionPerformed
        // TODO add your handling code here:
      
    AdopterProfile existingProfile = system.getAdopterProfileByUserId(currentUser.getUserId());

    JTextField monthlyIncomeField = new JTextField(
            existingProfile != null && existingProfile.getMonthlyIncome() != null
                    ? String.valueOf(existingProfile.getMonthlyIncome()) : ""
    );

    JTextField livingAreaField = new JTextField(
            existingProfile != null && existingProfile.getLivingArea() != null
                    ? existingProfile.getLivingArea() : ""
    );

    JSpinner numberOfPetsSpinner = new JSpinner(
            new SpinnerNumberModel(
                    existingProfile != null ? existingProfile.getNumberOfPets() : 0,
                    0, 20, 1
            )
    );

    JTextField experienceField = new JTextField(
            existingProfile != null && existingProfile.getPetRaisingExperience() != null
                    ? existingProfile.getPetRaisingExperience() : ""
    );

    JSpinner numberOfPeopleSpinner = new JSpinner(
            new SpinnerNumberModel(
                    existingProfile != null && existingProfile.getNumberOfPeople() != null
                            ? existingProfile.getNumberOfPeople() : 1,
                    1, 20, 1
            )
    );

    JComboBox<String> preferredPetTypeCombo = new JComboBox<>(
            new String[]{"Any", "Dog", "Cat", "Rabbit", "Bird", "Other"}
    );
    preferredPetTypeCombo.setEditable(true);

    if (existingProfile != null && existingProfile.getPreferredPetType() != null) {
        preferredPetTypeCombo.setSelectedItem(existingProfile.getPreferredPetType());
    }

    JPanel panel = new JPanel(new java.awt.GridLayout(0, 2, 8, 8));
    panel.add(new JLabel("Monthly Income:"));
    panel.add(monthlyIncomeField);

    panel.add(new JLabel("Living Area:"));
    panel.add(livingAreaField);

    panel.add(new JLabel("Number Of Pets:"));
    panel.add(numberOfPetsSpinner);

    panel.add(new JLabel("Pet Raising Experience:"));
    panel.add(experienceField);

    panel.add(new JLabel("Number Of People In Home:"));
    panel.add(numberOfPeopleSpinner);

    panel.add(new JLabel("Preferred Pet Type:"));
    panel.add(preferredPetTypeCombo);

    int result = JOptionPane.showConfirmDialog(
            this,
            panel,
            existingProfile == null ? "Create Adopter Profile" : "Update Adopter Profile",
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.PLAIN_MESSAGE
    );

    if (result != JOptionPane.OK_OPTION) {
        return;
    }

    Double monthlyIncome = null;
    String incomeText = monthlyIncomeField.getText().trim();
    if (!incomeText.isEmpty()) {
        try {
            monthlyIncome = Double.parseDouble(incomeText);
            if (monthlyIncome < 0) {
                JOptionPane.showMessageDialog(this, "Monthly income cannot be negative.");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Monthly income must be a valid number.");
            return;
        }
    }

    String livingArea = livingAreaField.getText().trim();
    String experience = experienceField.getText().trim();
    int numberOfPets = (Integer) numberOfPetsSpinner.getValue();
    Integer numberOfPeople = (Integer) numberOfPeopleSpinner.getValue();
    String preferredPetType = preferredPetTypeCombo.getSelectedItem() == null
            ? null
            : preferredPetTypeCombo.getSelectedItem().toString().trim();

    AdopterProfile profile = new AdopterProfile();
    profile.setUserId(currentUser.getUserId());
    profile.setMonthlyIncome(monthlyIncome);
    profile.setLivingArea(livingArea.isEmpty() ? null : livingArea);
    profile.setNumberOfPets(numberOfPets);
    profile.setPetRaisingExperience(experience.isEmpty() ? null : experience);
    profile.setNumberOfPeople(numberOfPeople);
    profile.setPreferredPetType(preferredPetType == null || preferredPetType.isEmpty() ? null : preferredPetType);

    boolean success = system.saveAdopterProfile(profile);

    if (success) {
        JOptionPane.showMessageDialog(this,
                existingProfile == null
                        ? "Adopter profile created successfully."
                        : "Adopter profile updated successfully.");
    } else {
        JOptionPane.showMessageDialog(this, "Failed to save adopter profile.");
    }

    }//GEN-LAST:event_ManageProfileButtonActionPerformed

    private void ViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewButtonActionPerformed
        // TODO add your handling code here:
        List<AdoptionApplication> applicationList =
            system.getApplicationsByUserId(currentUser.getUserId());

    showingPetList = false;

    DefaultTableModel model = new DefaultTableModel();
    model.setColumnIdentifiers(new String[]{
        "Application ID", "Pet ID", "Pet Name", "Species", "Breed", "Status"
    });

    for (AdoptionApplication application : applicationList) {
        model.addRow(new Object[]{
    application.getApplicationId(),
    application.getPetId(),
    application.getPetName(),
    application.getSpecies(),
    application.getBreed(),
    application.getStatus()
});
    }

    petTable.setModel(model);

    if (applicationList.isEmpty()) {
        JOptionPane.showMessageDialog(this, "You have not submitted any adoption applications yet.");
    }

    }//GEN-LAST:event_ViewButtonActionPerformed

    private void WithdrawApplicationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WithdrawApplicationButtonActionPerformed
        // TODO add your handling code here:
       
    if (showingPetList) {
        JOptionPane.showMessageDialog(this, "Please click View My Applications first.");
        return;
    }

    int selectedRow = petTable.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select an application first.");
        return;
    }

    Object applicationIdValue = petTable.getValueAt(selectedRow, 0);
    Object statusValue = petTable.getValueAt(selectedRow, 5);

    if (applicationIdValue == null || statusValue == null) {
        JOptionPane.showMessageDialog(this, "Selected row is invalid.");
        return;
    }

    int applicationId = Integer.parseInt(applicationIdValue.toString());
    String status = statusValue.toString();

    if (!"Submitted".equalsIgnoreCase(status)) {
        JOptionPane.showMessageDialog(this, "Only applications with status Submitted can be withdrawn.");
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to withdraw this application?",
            "Confirm Withdraw",
            JOptionPane.YES_NO_OPTION
    );

    if (confirm != JOptionPane.YES_OPTION) {
        return;
    }

    boolean success = system.withdrawAdoptionApplication(applicationId, currentUser.getUserId());

    if (success) {
        JOptionPane.showMessageDialog(this, "Application withdrawn successfully.");
        ViewButtonActionPerformed(null);
    } else {
        JOptionPane.showMessageDialog(this, "Failed to withdraw application.");
    
}
    }//GEN-LAST:event_WithdrawApplicationButtonActionPerformed

    
private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {
    new MainFrame().setVisible(true);
    this.dispose();
}

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdopterLabel;
    private javax.swing.JButton BrowsePetsButton;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JButton ManageProfileButton;
    private javax.swing.JScrollPane PetPane;
    private javax.swing.JButton SubmitApplicationButton;
    private javax.swing.JButton ViewButton;
    private javax.swing.JButton WithdrawApplicationButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable petTable;
    // End of variables declaration//GEN-END:variables

}