/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.vincent.petadoptionsystem.ui;

/**
 *
 * @author vincent
 */
import com.vincent.petadoptionsystem.model.User;
import com.vincent.petadoptionsystem.service.PetAdoptionSystem;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());
private PetAdoptionSystem system;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
    initComponents();
    system = PetAdoptionSystem.getInstance();
    PasswordPasswordField.setEchoChar((char) 0);

    DemoAccountsTextArea.setEditable(false);
    DemoAccountsTextArea.setLineWrap(true);
    DemoAccountsTextArea.setWrapStyleWord(true);
    DemoAccountsTextArea.setText(
            "Use your seeded demo accounts below:\n" +
            "Adopter: adopter@test.com / 123456\n" +
            "Surrender Owner: owner@test.com / 123456\n" +
            "Shelter Admin: shelter@test.com / 123456\n" +
            "Vet Staff: vet@test.com / 123456"
          
    );
    DemoAccountsTextArea.setCaretPosition(0);

    setLocationRelativeTo(null);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleLabel = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        EmailTextField = new javax.swing.JTextField();
        PasswordLabel = new javax.swing.JLabel();
        PasswordPasswordField = new javax.swing.JPasswordField();
        LoginButton = new javax.swing.JButton();
        DemoAccountsLabel = new javax.swing.JLabel();
        DemoAccountsScrollPane = new javax.swing.JScrollPane();
        DemoAccountsTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TitleLabel.setText("Pet Adoption System Login Portal");

        EmailLabel.setText("Email:");

        EmailTextField.addActionListener(this::EmailTextFieldActionPerformed);

        PasswordLabel.setText("Password:");

        PasswordPasswordField.setToolTipText("");
        PasswordPasswordField.addActionListener(this::PasswordPasswordFieldActionPerformed);

        LoginButton.setText("Login");
        LoginButton.addActionListener(this::LoginButtonActionPerformed);

        DemoAccountsLabel.setText("Demo Accounts");

        DemoAccountsTextArea.setColumns(20);
        DemoAccountsTextArea.setRows(5);
        DemoAccountsScrollPane.setViewportView(DemoAccountsTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(TitleLabel)
                        .addGap(138, 138, 138))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PasswordLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EmailLabel)
                                    .addComponent(DemoAccountsLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DemoAccountsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(150, 150, 150)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(PasswordPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(LoginButton))))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitleLabel)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DemoAccountsLabel)
                    .addComponent(DemoAccountsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailLabel)
                    .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordLabel)
                    .addComponent(PasswordPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(LoginButton)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EmailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailTextFieldActionPerformed

    private void PasswordPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordPasswordFieldActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // TODO add your handling code here:
        String email = EmailTextField.getText().trim();
String password = new String(PasswordPasswordField.getPassword());

User user = system.authenticateUser(email, password);

if (user != null) {
    JOptionPane.showMessageDialog(this,
            "Login successful! Role: " + user.getRole());

    openRoleWindow(user);
} else {
    JOptionPane.showMessageDialog(this,
            "Invalid email or password.",
            "Login Failed",
            JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_LoginButtonActionPerformed
private void openRoleWindow(User user) {
    switch (user.getRole()) {
        case "Adopter":
            new AdopterFrame(user).setVisible(true);
            break;
        case "SurrenderOwner":
            new SurrenderOwnerFrame(user).setVisible(true);
            break;
        case "ShelterAdmin":
            new ShelterAdminFrame(user).setVisible(true);
            break;
        case "VetStaff":
            new VetStaffFrame(user).setVisible(true);
            break;
        default:
            JOptionPane.showMessageDialog(this, "Unknown role.");
            return;
    }

    this.dispose();
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DemoAccountsLabel;
    private javax.swing.JScrollPane DemoAccountsScrollPane;
    private javax.swing.JTextArea DemoAccountsTextArea;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JTextField EmailTextField;
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JPasswordField PasswordPasswordField;
    private javax.swing.JLabel TitleLabel;
    // End of variables declaration//GEN-END:variables
}
