/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.vincent.petadoptionsystem.ui;

/**
 *
 * @author vincent
 */
public class ShelterAdminFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ShelterAdminFrame.class.getName());

    /**
     * Creates new form ShelterAdminFrame
     */
    public ShelterAdminFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ShelterLabel = new javax.swing.JLabel();
        ReviewButton = new javax.swing.JButton();
        ReviewAdoptionButton = new javax.swing.JButton();
        SendButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ShelterLabel.setText("Shelter Admin Dashboard");

        ReviewButton.setText("Review Surrender Requests");

        ReviewAdoptionButton.setText("Review Adoption Applications");
        ReviewAdoptionButton.addActionListener(this::ReviewAdoptionButtonActionPerformed);

        SendButton.setText("Send Medical Check Request");

        LogoutButton.setText("Logout");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(ShelterLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ReviewAdoptionButton)
                            .addComponent(ReviewButton)
                            .addComponent(SendButton)
                            .addComponent(LogoutButton))))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(ShelterLabel)
                .addGap(26, 26, 26)
                .addComponent(ReviewButton)
                .addGap(34, 34, 34)
                .addComponent(ReviewAdoptionButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(SendButton)
                .addGap(34, 34, 34)
                .addComponent(LogoutButton)
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReviewAdoptionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReviewAdoptionButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReviewAdoptionButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ShelterAdminFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogoutButton;
    private javax.swing.JButton ReviewAdoptionButton;
    private javax.swing.JButton ReviewButton;
    private javax.swing.JButton SendButton;
    private javax.swing.JLabel ShelterLabel;
    // End of variables declaration//GEN-END:variables
}
