/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.vincent.petadoptionsystem.ui;

/**
 *
 * @author Yuedong Xu
 */
import com.vincent.petadoptionsystem.model.SurrenderRequest;
import com.vincent.petadoptionsystem.model.User;
import com.vincent.petadoptionsystem.service.PetAdoptionSystem;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
public class SurrenderOwnerFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SurrenderOwnerFrame.class.getName());
private final PetAdoptionSystem system;
private final User currentUser;
    /**
     * Creates new form SurrenderOwnerFrame
     * @param user
     */
    public SurrenderOwnerFrame(User user) {
    this.currentUser = user;
    this.system = PetAdoptionSystem.getInstance();
    initComponents();
    setLocationRelativeTo(null);
}

public SurrenderOwnerFrame() {
    this.currentUser = null;
    this.system = PetAdoptionSystem.getInstance();
    initComponents();
    setLocationRelativeTo(null);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SurrenderLabel = new javax.swing.JLabel();
        SubmitSurrenderButton = new javax.swing.JButton();
        ViewMyRequestsButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();
        PetNameTextField = new javax.swing.JTextField();
        DescriptionScrollPane = new javax.swing.JScrollPane();
        DescriptionTextArea = new javax.swing.JTextArea();
        PetNameLabel = new javax.swing.JLabel();
        ReasonLabel = new javax.swing.JLabel();
        DescriptionLabel = new javax.swing.JLabel();
        SpeciesLabel = new javax.swing.JLabel();
        BreedLabel = new javax.swing.JLabel();
        BreedTextField = new javax.swing.JTextField();
        AgeLabel = new javax.swing.JLabel();
        GenderLabel = new javax.swing.JLabel();
        ColorLabel = new javax.swing.JLabel();
        ColorTextField = new javax.swing.JTextField();
        HealthLabel = new javax.swing.JLabel();
        WeightLabel = new javax.swing.JLabel();
        WeightTextField = new javax.swing.JTextField();
        SpeciesComboBox = new javax.swing.JComboBox<>();
        GenderComboBox = new javax.swing.JComboBox<>();
        HealthStatusComboBox = new javax.swing.JComboBox<>();
        AgeSpinner = new javax.swing.JSpinner();
        ReasonComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SurrenderLabel.setText("Surrender Owner Dashboard");

        SubmitSurrenderButton.setText("Submit Surrender Request");
        SubmitSurrenderButton.addActionListener(this::SubmitSurrenderButtonActionPerformed);

        ViewMyRequestsButton.setText("View My Requests");
        ViewMyRequestsButton.addActionListener(this::ViewMyRequestsButtonActionPerformed);

        LogoutButton.setText("Logout");
        LogoutButton.addActionListener(this::LogoutButtonActionPerformed);

        DescriptionTextArea.setColumns(20);
        DescriptionTextArea.setRows(5);
        DescriptionScrollPane.setViewportView(DescriptionTextArea);

        PetNameLabel.setText("Pet Name:");

        ReasonLabel.setText("Reason:");

        DescriptionLabel.setText("Description:");

        SpeciesLabel.setText("Species:");

        BreedLabel.setText("Breed:");

        BreedTextField.addActionListener(this::BreedTextFieldActionPerformed);

        AgeLabel.setText("Age:");

        GenderLabel.setText("Gender:");

        ColorLabel.setText("Color:");

        ColorTextField.addActionListener(this::ColorTextFieldActionPerformed);

        HealthLabel.setText("Health Status:");

        WeightLabel.setText("Weight(kg):");

        WeightTextField.addActionListener(this::WeightTextFieldActionPerformed);

        SpeciesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please select species", "Dog", "Cat", "Rabbit", "Bird", "Hamster", "Other" }));

        GenderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please select gender", "Male", "Female" }));

        HealthStatusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please select health status", "Healthy", "Needs Treatment", "Under Observation", "Injured", "Unknown" }));

        ReasonComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please select reason", "Moving", "Financial Difficulty", "Allergy", "Behavioral Issues", "Cannot Care Anymore", "Other" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(SubmitSurrenderButton)
                .addGap(125, 125, 125)
                .addComponent(ViewMyRequestsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addComponent(LogoutButton)
                .addGap(121, 121, 121))
            .addGroup(layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AgeLabel)
                            .addComponent(SpeciesLabel)
                            .addComponent(ColorLabel)
                            .addComponent(HealthLabel)
                            .addComponent(ReasonLabel)
                            .addComponent(DescriptionLabel)
                            .addComponent(WeightLabel)
                            .addComponent(GenderLabel))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(173, 173, 173)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PetNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SpeciesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(GenderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(HealthStatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(ColorTextField)
                                        .addComponent(DescriptionScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                                        .addComponent(WeightTextField))
                                    .addComponent(BreedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AgeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ReasonComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(181, 181, 181))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PetNameLabel)
                            .addComponent(BreedLabel))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(321, 321, 321)
                .addComponent(SurrenderLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(SurrenderLabel)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PetNameLabel)
                    .addComponent(PetNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SpeciesLabel)
                    .addComponent(SpeciesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BreedLabel)
                    .addComponent(BreedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgeLabel)
                    .addComponent(AgeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GenderLabel)
                    .addComponent(GenderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(DescriptionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(WeightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(WeightLabel))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ColorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ColorLabel))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HealthLabel)
                            .addComponent(HealthStatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ReasonLabel)
                            .addComponent(ReasonComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addComponent(DescriptionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SubmitSurrenderButton)
                    .addComponent(ViewMyRequestsButton)
                    .addComponent(LogoutButton))
                .addGap(87, 87, 87))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitSurrenderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitSurrenderButtonActionPerformed
        // TODO add your handling code here:
       if (currentUser == null) {
    JOptionPane.showMessageDialog(this, "Current user is missing.");
    return;
}

String petName = PetNameTextField.getText().trim();
String species = SpeciesComboBox.getSelectedItem().toString();
String breed = BreedTextField.getText().trim();
int age = (int) AgeSpinner.getValue();
String gender = GenderComboBox.getSelectedItem().toString();
String weightInput = WeightTextField.getText().trim();
String color = ColorTextField.getText().trim();
String healthStatus = HealthStatusComboBox.getSelectedItem().toString();
String reason = ReasonComboBox.getSelectedItem().toString();
String description = DescriptionTextArea.getText().trim();

if ("Please select species".equals(species)) {
    JOptionPane.showMessageDialog(this, "Please select species.");
    return;
}

if ("Please select gender".equals(gender)) {
    JOptionPane.showMessageDialog(this, "Please select gender.");
    return;
}

if ("Please select health status".equals(healthStatus)) {
    JOptionPane.showMessageDialog(this, "Please select health status.");
    return;
}

if ("Please select reason".equals(reason)) {
    JOptionPane.showMessageDialog(this, "Please select surrender reason.");
    return;
}
if (petName.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Please enter pet name.");
    return;
}

if (breed.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Please enter breed.");
    return;
}

if (weightInput.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Please enter weight.");
    return;
}

if (age < 0) {
    JOptionPane.showMessageDialog(this, "Please enter a valid age.");
    return;
}
double weight;
try {
    weight = Double.parseDouble(weightInput);
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Weight must be a number (kg).");
    return;
}

if (color.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Please enter color.");
    return;
}

boolean success = system.createSurrenderRequest(
        currentUser.getUserId(),
        petName,
        species,
        breed,
        age,
        gender,
        weight,
        color,
        healthStatus,
        reason,
        description
);

if (success) {
    JOptionPane.showMessageDialog(this, "Surrender request submitted successfully.");

    PetNameTextField.setText("");
    BreedTextField.setText("");
    WeightTextField.setText("");
    ColorTextField.setText("");
    DescriptionTextArea.setText("");

    AgeSpinner.setValue(0);

    SpeciesComboBox.setSelectedIndex(0);
    GenderComboBox.setSelectedIndex(0);
    HealthStatusComboBox.setSelectedIndex(0);
    ReasonComboBox.setSelectedIndex(0);
} else {
    JOptionPane.showMessageDialog(this, "Submission failed.");
}
    }//GEN-LAST:event_SubmitSurrenderButtonActionPerformed

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        // TODO add your handling code here:
        new MainFrame().setVisible(true);
this.dispose();
    }//GEN-LAST:event_LogoutButtonActionPerformed

    private void ViewMyRequestsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewMyRequestsButtonActionPerformed
        // TODO add your handling code here:
        if (currentUser == null) {
    JOptionPane.showMessageDialog(this, "Current user is missing.");
    return;
}

List<SurrenderRequest> requestList = system.getSurrenderRequestsByUserId(currentUser.getUserId());

if (requestList.isEmpty()) {
    JOptionPane.showMessageDialog(this, "You have not submitted any surrender requests yet.");
    return;
}

StringBuilder sb = new StringBuilder();
for (SurrenderRequest request : requestList) {
    sb.append("Request ID: ").append(request.getSurrenderRequestId()).append("\n")
      .append("Pet ID: ").append(request.getPetId()).append("\n")
      .append("Pet Name: ").append(request.getPetName()).append("\n")
      .append("Species: ").append(request.getSpecies()).append("\n")
      .append("Breed: ").append(request.getBreed()).append("\n")
      .append("Age: ").append(request.getAge()).append("\n")
      .append("Gender: ").append(request.getGender()).append("\n")
      .append("Weight (kg): ").append(request.getWeight()).append("\n")
      .append("Color: ").append(request.getColor()).append("\n")
      .append("Health Status: ").append(request.getHealthStatus()).append("\n")
      .append("Status: ").append(request.getStatus()).append("\n")
      .append("Reason: ").append(request.getReason()).append("\n")
      .append("Description: ").append(request.getDescription()).append("\n")
      .append("Request Date: ").append(request.getRequestDate()).append("\n")
      .append("Processed At: ").append(request.getProcessedAt()).append("\n")
      .append("--------------------------------------\n");
}

JTextArea textArea = new JTextArea(sb.toString(), 22, 50);
textArea.setEditable(false);
textArea.setLineWrap(true);
textArea.setWrapStyleWord(true);

JOptionPane.showMessageDialog(
        this,
        new JScrollPane(textArea),
        "My Surrender Requests",
        JOptionPane.INFORMATION_MESSAGE
);
    }//GEN-LAST:event_ViewMyRequestsButtonActionPerformed

    private void BreedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BreedTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BreedTextFieldActionPerformed

    private void ColorTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColorTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ColorTextFieldActionPerformed

    private void WeightTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WeightTextFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_WeightTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SurrenderOwnerFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgeLabel;
    private javax.swing.JSpinner AgeSpinner;
    private javax.swing.JLabel BreedLabel;
    private javax.swing.JTextField BreedTextField;
    private javax.swing.JLabel ColorLabel;
    private javax.swing.JTextField ColorTextField;
    private javax.swing.JLabel DescriptionLabel;
    private javax.swing.JScrollPane DescriptionScrollPane;
    private javax.swing.JTextArea DescriptionTextArea;
    private javax.swing.JComboBox<String> GenderComboBox;
    private javax.swing.JLabel GenderLabel;
    private javax.swing.JLabel HealthLabel;
    private javax.swing.JComboBox<String> HealthStatusComboBox;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JLabel PetNameLabel;
    private javax.swing.JTextField PetNameTextField;
    private javax.swing.JComboBox<String> ReasonComboBox;
    private javax.swing.JLabel ReasonLabel;
    private javax.swing.JComboBox<String> SpeciesComboBox;
    private javax.swing.JLabel SpeciesLabel;
    private javax.swing.JButton SubmitSurrenderButton;
    private javax.swing.JLabel SurrenderLabel;
    private javax.swing.JButton ViewMyRequestsButton;
    private javax.swing.JLabel WeightLabel;
    private javax.swing.JTextField WeightTextField;
    // End of variables declaration//GEN-END:variables
}
