/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.vincent.petadoptionsystem.ui;

/**
 *
 * @author vincent
 */
import com.vincent.petadoptionsystem.model.SurrenderRequest;
import com.vincent.petadoptionsystem.model.User;
import com.vincent.petadoptionsystem.service.PetAdoptionSystem;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
public class SurrenderOwnerFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SurrenderOwnerFrame.class.getName());
private final PetAdoptionSystem system;
private final User currentUser;
    /**
     * Creates new form SurrenderOwnerFrame
     */
    public SurrenderOwnerFrame(User user) {
    this.currentUser = user;
    this.system = PetAdoptionSystem.getInstance();
    initComponents();
    setLocationRelativeTo(null);
}

public SurrenderOwnerFrame() {
    this.currentUser = null;
    this.system = PetAdoptionSystem.getInstance();
    initComponents();
    setLocationRelativeTo(null);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SurrenderLabel = new javax.swing.JLabel();
        SubmitSurrenderButton = new javax.swing.JButton();
        ViewMyRequestsButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();
        PetIdTextField = new javax.swing.JTextField();
        ReasonTextField = new javax.swing.JTextField();
        DescriptionScrollBar = new javax.swing.JScrollPane();
        DescriptionTextArea = new javax.swing.JTextArea();
        PetIdLabel = new javax.swing.JLabel();
        ReasonLabel = new javax.swing.JLabel();
        DescriptionLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SurrenderLabel.setText("Surrender Owner Dashboard");

        SubmitSurrenderButton.setText("Submit Surrender Request");
        SubmitSurrenderButton.addActionListener(this::SubmitSurrenderButtonActionPerformed);

        ViewMyRequestsButton.setText("View My Requests");
        ViewMyRequestsButton.addActionListener(this::ViewMyRequestsButtonActionPerformed);

        LogoutButton.setText("Logout");
        LogoutButton.addActionListener(this::LogoutButtonActionPerformed);

        ReasonTextField.addActionListener(this::ReasonTextFieldActionPerformed);

        DescriptionTextArea.setColumns(20);
        DescriptionTextArea.setRows(5);
        DescriptionScrollBar.setViewportView(DescriptionTextArea);

        PetIdLabel.setText("Pet ID:");

        ReasonLabel.setText("Reason:");

        DescriptionLabel.setText("Description:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(SurrenderLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ViewMyRequestsButton)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LogoutButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(DescriptionLabel)
                                .addGap(237, 237, 237))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SubmitSurrenderButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 260, Short.MAX_VALUE)
                                .addComponent(PetIdLabel)
                                .addGap(18, 18, 18)
                                .addComponent(PetIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ReasonLabel)
                        .addGap(18, 18, 18)
                        .addComponent(ReasonTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(107, 107, 107))
            .addGroup(layout.createSequentialGroup()
                .addGap(540, 540, 540)
                .addComponent(DescriptionScrollBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(SurrenderLabel)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(SubmitSurrenderButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PetIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PetIdLabel))))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReasonTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReasonLabel))
                .addGap(5, 5, 5)
                .addComponent(ViewMyRequestsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(LogoutButton)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(DescriptionScrollBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(DescriptionLabel)
                        .addGap(61, 61, 61))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitSurrenderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitSurrenderButtonActionPerformed
        // TODO add your handling code here:
       if (currentUser == null) {
    JOptionPane.showMessageDialog(this, "Current user is missing.");
    return;
}

String petIdInput = PetIdTextField.getText().trim();
String reason = ReasonTextField.getText().trim();
String description = DescriptionTextArea.getText().trim();

if (petIdInput.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Please enter Pet ID.");
    return;
}

int petId;
try {
    petId = Integer.parseInt(petIdInput);
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Pet ID must be a number.");
    return;
}

if (reason.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Please enter surrender reason.");
    return;
}

boolean success = system.createSurrenderRequest(
        currentUser.getUserId(),
        petId,
        reason,
        description
);

if (success) {
    JOptionPane.showMessageDialog(this, "Surrender request submitted successfully.");

    PetIdTextField.setText("");
    ReasonTextField.setText("");
    DescriptionTextArea.setText("");
} else {
    JOptionPane.showMessageDialog(this, "Submission failed. You may already have an active request for this pet.");
}
    }//GEN-LAST:event_SubmitSurrenderButtonActionPerformed

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        // TODO add your handling code here:
        new MainFrame().setVisible(true);
this.dispose();
    }//GEN-LAST:event_LogoutButtonActionPerformed

    private void ViewMyRequestsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewMyRequestsButtonActionPerformed
        // TODO add your handling code here:
        if (currentUser == null) {
    JOptionPane.showMessageDialog(this, "Current user is missing.");
    return;
}

List<SurrenderRequest> requestList = system.getSurrenderRequestsByUserId(currentUser.getUserId());

if (requestList.isEmpty()) {
    JOptionPane.showMessageDialog(this, "You have not submitted any surrender requests yet.");
    return;
}

StringBuilder sb = new StringBuilder();
for (SurrenderRequest request : requestList) {
    sb.append("Request ID: ").append(request.getSurrenderRequestId()).append("\n")
      .append("Pet ID: ").append(request.getPetId()).append("\n")
      .append("Pet Name: ").append(request.getPetName()).append("\n")
      .append("Status: ").append(request.getStatus()).append("\n")
      .append("Reason: ").append(request.getReason()).append("\n")
      .append("Description: ").append(request.getDescription()).append("\n")
      .append("Request Date: ").append(request.getRequestDate()).append("\n")
      .append("Processed At: ").append(request.getProcessedAt()).append("\n")
      .append("--------------------------------------\n");
}

JTextArea textArea = new JTextArea(sb.toString(), 18, 40);
textArea.setEditable(false);
textArea.setLineWrap(true);
textArea.setWrapStyleWord(true);

JOptionPane.showMessageDialog(
        this,
        new JScrollPane(textArea),
        "My Surrender Requests",
        JOptionPane.INFORMATION_MESSAGE
);
    }//GEN-LAST:event_ViewMyRequestsButtonActionPerformed

    private void ReasonTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReasonTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReasonTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SurrenderOwnerFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DescriptionLabel;
    private javax.swing.JScrollPane DescriptionScrollBar;
    private javax.swing.JTextArea DescriptionTextArea;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JLabel PetIdLabel;
    private javax.swing.JTextField PetIdTextField;
    private javax.swing.JLabel ReasonLabel;
    private javax.swing.JTextField ReasonTextField;
    private javax.swing.JButton SubmitSurrenderButton;
    private javax.swing.JLabel SurrenderLabel;
    private javax.swing.JButton ViewMyRequestsButton;
    // End of variables declaration//GEN-END:variables
}
